--[[-- License Plate Autogenerated Vehicle Configurations
@copyright 2019 Limelight Gaming
@release 3-1-2
@author Doctor Internet et al.
--]]--

local PLATE = PLATE_SHARED

PLATE:RegisterPlate("2016 Ford Police Interceptor Utility", {
	pos = Vector(0, 115.5, 28),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -112, 49),
	ang = Angle(0, 0, 78),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("Airboat", {
	pos = Vector(0, 45.4, 29),
	ang = Angle(0, 180, 41),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("Jalopy", {
	pos = Vector(1.8, 76, 16),
	ang = Angle(1, 179, 100),
	scale = 1.1,
	bg = {id = false, val = {}}
}, {
	pos = Vector(-1.5, -141, 41),
	ang = Angle(-1, -1, 104.2),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("Jeep", {
	pos = Vector(0, 64.46, 15),
	ang = Angle(0, 180, 90),
	scale = 1.2,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.28, -98, 34),
	ang = Angle(0, 0, 90),
	scale = 1.2,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vcars_bmw2002", {
	pos = Vector(0, -98.58, 30.4),
	ang = Angle(0, 0, 88.05),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vcars_bmwm3e30", {
	pos = Vector(0, -98.2, 30.21),
	ang = Angle(0, 0, 77.82),
	scale = 1.09,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vcars_infinitig35", {
	pos = Vector(0, -107.25, 21.89),
	ang = Angle(0, 0, 90),
	scale = 0.487,
	bg = {id = 6, val = {[1] = {pos = Vector(0, -107.33, 21.89), ang = Angle(0, 0, 91.12), scale = 0.487}, [2] = {pos = Vector(0, -106.23, 21.7), ang = Angle(0, 0, 73.39), scale = 0.552}, [3] = {pos = Vector(0, -109.75, 19.22), ang = Angle(0, 0, 71.69), scale = 1.134}, [4] = {pos = Vector(0, -107.75, 22.22), ang = Angle(0, 0, 72.84), scale = 0.41}, [5] = {pos = Vector(0, -107.23, 21.89), ang = Angle(0, 0, 90), scale = 0.487}, [6] = {pos = Vector(0, -107.25, 21.89), ang = Angle(0, 0, 90), scale = 0.487}}}
})

PLATE:RegisterPlate("vcars_hondacivicep3", {
	pos = Vector(0, 98.88, 19.82),
	ang = Angle(0, 180, 90),
	scale = 0.852,
	bg = {id = 1, val = {[1] = {pos = Vector(0, 98.88, 19.82), ang = Angle(0, 180, 90), scale = 0.852}, [2] = {pos = Vector(0, 98.88, 19.82), ang = Angle(0, 180, 90), scale = 0.852}, [4] = {pos = Vector(0, 98.88, 19.82), ang = Angle(0, 180, 90), scale = 0.852}, [6] = {pos = Vector(0, 98.88, 19.82), ang = Angle(0, 180, 90), scale = 0.852}}}
}, {
	pos = Vector(0, -95.24, 38.26),
	ang = Angle(0, 0, 81.72),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vcars_bmwm3e46", {
	pos = Vector(0, -103.05, 36.83),
	ang = Angle(0, 0, 81.17),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vcars_bmwm6e63", {
	pos = Vector(0, -112.21, 20.24),
	ang = Angle(-0.54, 0, 90.11),
	scale = 1.225,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vcars_bmwm3gts", {
	pos = Vector(0, -105.05, 37.32),
	ang = Angle(0, 0, 74.97),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vcars_bmwm4f82", {
	pos = Vector(0, -110.07, 37.92),
	ang = Angle(0, 0, 75.49),
	scale = 0.74,
	bg = {id = 6, val = {[2] = {pos = Vector(0, -109.86, 37.92), ang = Angle(0, 0, 74.65), scale = 1.104}}}
})

PLATE:RegisterPlate("vcars_lamboaventadorsv", {
	pos = Vector(0, -108.36, 34.9),
	ang = Angle(0, 0, 73.56),
	scale = 0.659,
	bg = {id = 2, val = {[1] = {pos = Vector(0, -107.98, 34.38), ang = Angle(0, 0, 71.85), scale = 0.998}}}
})

PLATE:RegisterPlate("vcars_ferrari488gtb", {
	pos = Vector(0, -102.02, 28.49),
	ang = Angle(-0.5, 0, 69.06),
	scale = 0.738,
	bg = {id = 4, val = {[0] = {pos = Vector(0, -101.63, 28.17), ang = Angle(-0.5, 0, 70.51), scale = 0.823}}}
})

PLATE:RegisterPlate("vcars_bmwm2comp", {
	pos = Vector(-0.29, -102, 38.4),
	ang = Angle(0, 0, 74.08),
	bg = {id = 1, val = {[0] = {pos = Vector(-0.29, -101.98, 37.8), ang = Angle(0, 0, 74.08), scale = 1.282}}}
})

PLATE:RegisterPlate("vcars_bmwm4lb", {
	pos = Vector(0, -113.43, 34.71),
	ang = Angle(0, 0, 75.6),
	scale = 1.082,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vcars_bmwm5f10", {
	pos = Vector(0, -120.68, 38.55),
	ang = Angle(0.18, 0, 75.94),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vcars_bmwx6m", {
	pos = Vector(3.45, -123.05, 50.52),
	ang = Angle(0, 0, 81.53),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vcars_bmwz4m", {
	pos = Vector(0, -98.55, 19.79),
	ang = Angle(0, 0, 84.58),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vcars_lamboperformante", {
	pos = Vector(-0.28, -101.66, 18.13),
	ang = Angle(0, 0, 84.1),
	bg = {id = 1, val = {[1] = {pos = Vector(-0.28, -101.66, 18.13), ang = Angle(0, 0, 84.1)}}}
})

PLATE:RegisterPlate("vcars_nissangtr12", {
	pos = Vector(0, -111.65, 31.45),
	ang = Angle(0, 0, 79.88),
	scale = 1.188,
	bg = {id = 7, val = {[1] = {pos = Vector(0, -111.65, 31.45), ang = Angle(0, 0, 79.88), scale = 1.188}}}
})

PLATE:RegisterPlate("vcars_porsche911carrera", {
	pos = Vector(0, -109.15, 23.13),
	ang = Angle(0, 0, 79.84),
	scale = 0.851,
	bg = {id = 6, val = {[1] = {pos = Vector(0, -109.04, 22.93), ang = Angle(0, 0, 79.84), scale = 1.041}}}
})

PLATE:RegisterPlate("buffalo_marked_toki", {
	pos = Vector(0, -112.3, 38.37),
	ang = Angle(0, 0, 80.28),
	scale = 0.93,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("fugitivepd_toki", {
	pos = Vector(0, 107.77, 17.36),
	ang = Angle(0, 180, 90),
	scale = 0.977,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -120.67, 22.34),
	ang = Angle(0, 0, 90),
	scale = 1.086,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("policet_toki", {
	pos = Vector(0, 119.96, 24.36),
	ang = Angle(0.17, 180, 97.79),
	scale = 0.96,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -135.3, 28.06),
	ang = Angle(0, 0, 90),
	scale = 0.936,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("toki_baller1", {
	pos = Vector(0, -141.84, 52.05),
	ang = Angle(0, 0, 84.03),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("insurgent_toki", {
	pos = Vector(0, -157.41, 41.04),
	ang = Angle(0, 0, 90),
	scale = 1.044,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("asteropesec_toki", {
	pos = Vector(0, 112.05, 16.47),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -107.61, 37.25),
	ang = Angle(0, 0, 86.04),
	scale = 1.144,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vacca_toki", {
	pos = Vector(0, 115.28, 17.26),
	ang = Angle(0, 180, 114.03),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -95.44, 19.07),
	ang = Angle(0, 0, 82.44),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("pol_stainer2_toki", {
	pos = Vector(-0.06, 129.62, 22.72),
	ang = Angle(0, 180, 90),
	scale = 1.045,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -122.47, 38.52),
	ang = Angle(0, 0, 79.69),
	scale = 1.056,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("pol_stainer_toki", {
	pos = Vector(-0.06, 134.97, 23.44),
	ang = Angle(0, 180, 90),
	scale = 1.045,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -127.53, 40),
	ang = Angle(0, 0, 79.69),
	scale = 1.056,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("trailer_glass_lw", {
	pos = Vector(0, -226.97, 25.75),
	ang = Angle(0, 0, 90),
	scale = 0.666,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, 0, 0),
	ang = Angle(0, 0, 0),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("metrohd_porsche_panamera", {
	pos = Vector(0, -124.19, 32.11),
	ang = Angle(0, 0, 74.19),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("nismor35_sgm", {
	pos = Vector(0.45, -103.72, 27.32),
	ang = Angle(0, 0, 78.77),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("crsk_mercedes_vito_panel_2014", {
	pos = Vector(0, 116, 20.96),
	ang = Angle(0, 180, 90),
	scale = 0.751,
	bg = {id = 3, val = {[1] = {pos = Vector(0, 116, 20.96), ang = Angle(0, 180, 90), scale = 0.751}}}
}, {
	pos = Vector(-16.99, -120.14, 39.84),
	ang = Angle(-0.16, -2.57, 76.8),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("crsk_alfaromeo_8cspider", {
	pos = Vector(0, -105.8, 35.1),
	ang = Angle(0, 0, 77),
	scale = 0.92,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("crsk_paz_3205", {
	pos = Vector(0, 156, 27),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -161.9, 55.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("asc_kz1r", {
	pos = Vector(0, 107.8, 20),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -107.5, 29.3),
	ang = Angle(0, 0, 85),
	scale = 0.85,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("astonmartin_cygnet_lw", {
	pos = Vector(0, 73.84, 22.93),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -71, 27),
	ang = Angle(0, 0, 72),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("audi_r18", {
	pos = Vector(0, 105.5, 18.2),
	ang = Angle(0, 180, 25),
	scale = 0.5,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("austin_healey_3000_lw", {
	pos = Vector(0, 94, 15),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bentley_blower_lw", {
	pos = Vector(-9.2, 129, 23.6),
	ang = Angle(0, 180, 90),
	scale = 0.9,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -85, 38),
	ang = Angle(0, 0, 82),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bentley_arnage", {
	pos = Vector(0, 135.3, 21.8),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -113.65, 37.25),
	ang = Angle(0, 0, 67.5),
	scale = 0.9,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bently_pmcontinental", {
	pos = Vector(0, 120.5, 26.9),
	ang = Angle(0, 180, 80),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -123.57, 31.48),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bmw_530d_touring_lw", {
	pos = Vector(0, -114.5, 36),
	ang = Angle(0, 0, 78.9),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, 117.2, 22),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bmw_850csi_lw", {
	pos = Vector(0, -108.5, 33),
	ang = Angle(0, 0, 78.9),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, 113.5, 18),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bmw_i8_lw", {
	pos = Vector(0, 117.5, 18.7),
	ang = Angle(0, 180, 88),
	scale = 0.87,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -114.6, 25),
	ang = Angle(0, 0, 74),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bmw_m3_e30_lw", {
	pos = Vector(-0.13, 105.81, 20.43),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.22, -106.88, 30.46),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bmw_m5e39_lw", {
	pos = Vector(-0.66, 119, 21.18),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.28, -115.22, 36.65),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bmw_x5_48i_lw", {
	pos = Vector(0, 122, 27),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -114, 47),
	ang = Angle(0, 0, 83),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bugatti_veyron_grandsport_lw", {
	pos = Vector(0, -108, 28.68),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("cad_eldorado", {
	pos = Vector(0, 136.4, 23),
	ang = Angle(0, 180, 90),
	scale = 0.9,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -132.8, 24),
	ang = Angle(0, 0, 90),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("cad_eldorado_limo", {
	pos = Vector(0, 136.5, 23),
	ang = Angle(0, 180, 90),
	scale = 0.9,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -241.4, 24),
	ang = Angle(0, 0, 90),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("caterham_r500_superlight_lw", {
	pos = Vector(0, 70.15, 25.7),
	ang = Angle(0, 180, 27),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -73.4, 17.68),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("chev_cucv_lw", {
	pos = Vector(0, 106.3, 37.2),
	ang = Angle(0, 180, 105),
	scale = 0.9,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -139.5, 31.5),
	ang = Angle(0, 0, 90),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("chev_cucv_chassis_lw", {
	pos = Vector(24.5, 103.25, 36.5),
	ang = Angle(0, 180, 90),
	scale = 0.9,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -133.2, 33.25),
	ang = Angle(0, 0, 90),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("chev_cucv_flatbed_lw", {
	pos = Vector(0, 106.3, 37.2),
	ang = Angle(0, 180, 105),
	scale = 0.9,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -133.2, 33.25),
	ang = Angle(0, 0, 90),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("chev_impala_09", {
	pos = Vector(0, 121.7, 23),
	ang = Angle(0, 180, 75),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -120, 28),
	ang = Angle(0, 0, 83),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("chev_impala_09_taxi", {
	pos = Vector(0, 121.7, 23),
	ang = Angle(0, 180, 75),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -120, 28),
	ang = Angle(0, 0, 83),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("chev_nascar", {
	pos = Vector(0, 127.7, 19),
	ang = Angle(0, 180, 80),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -120, 28),
	ang = Angle(0, 0, 83),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("chev_suburban", {
	pos = Vector(0, 135.7, 22),
	ang = Angle(0, 180, 113),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -130, 46.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("chev_tahoe_lw", {
	pos = Vector(0, 114.7, 20),
	ang = Angle(0, 180, 104),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -114, 46.5),
	ang = Angle(0, 0, 84),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("citroen_ds3_rally_lw", {
	pos = Vector(0, 93.7, 20),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -93, 21),
	ang = Angle(0, 0, 65),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("dacia_duster_lw", {
	pos = Vector(0, 96.7, 25),
	ang = Angle(0, 180, 103),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -108, 42),
	ang = Angle(0, 0, 75),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("detomaso_pantera_lw", {
	pos = Vector(0, -101.5, 29),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("dodge_charger_70_fnf_lw", {
	pos = Vector(0, 126.4, 31),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -128, 27),
	ang = Angle(0, 0, 89),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("dodge_charger_2015_lw", {
	pos = Vector(0, 124.5, 25),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -127, 29.7),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("dodge_monaco_lw", {
	pos = Vector(0, 129.5, 18),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -133, 25.7),
	ang = Angle(0, 0, 75),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("dodge_ram_1500_outdoorsman_lw", {
	pos = Vector(0, 148.7, 25),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -120, 32),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("dodge_viper", {
	pos = Vector(0, -103, 40.7),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ferrari_365gts_lw", {
	pos = Vector(0, -103.5, 35.7),
	ang = Angle(0, 0, 62),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ferrari_458_lw", {
	pos = Vector(0, -111.12, 28.5),
	ang = Angle(0, 0, 70),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ferrari_f40_lw", {
	pos = Vector(0, 107.5, 10),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -109.12, 21.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ferrari_ff_lw", {
	pos = Vector(0, 122.62, 15),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -118.12, 29.5),
	ang = Angle(0, 0, 75),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ferrari_laferrari_lw", {
	pos = Vector(0, -109.12, 24.5),
	ang = Angle(0, 0, 66),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("fiat595", {
	pos = Vector(0, 76.62, 18),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -70, 29.5),
	ang = Angle(0, 0, 65),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ford_capri_rs3100_lw", {
	pos = Vector(0, 101.62, 19),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -104.12, 31.9),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ford_foxbody_stock_lw", {
	pos = Vector(0, 114.62, 19),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -106.32, 34),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("fordcountry", {
	pos = Vector(0, 132.5, 19),
	ang = Angle(0, 180, 105),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -133.32, 20),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ford_mustang_whitegirl_lw", {
	pos = Vector(0, 109.1, 19),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -116.32, 26),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ford_rs200_lw", {
	pos = Vector(0, 100.7, 18),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -91.32, 31.7),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ford_falcon_xb_lw", {
	pos = Vector(0, 112.7, 17),
	ang = Angle(0, 180, 120),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -121.42, 27),
	ang = Angle(0, 0, 100),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("gmc_savana_lw", {
	pos = Vector(-1.47, 132.78, 17.15),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(15.9, -131.37, 48),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("gmc_savana_news_lw", {
	pos = Vector(0, 137, 24.15),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(15.9, -131.37, 48),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("gmc_typhoon", {
	pos = Vector(0, 116.7, 24),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -98.42, 22.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("gmc_yukon_lw", {
	pos = Vector(0, 136.7, 28),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -132.42, 32.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("honda_nsxr_lw", {
	pos = Vector(0, 111.7, 18),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -111.42, 24.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("hot_twinmill_lw", {
	pos = Vector(12.25, 119.84, 19.21),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.16, -91.47, 25.71),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("hummer_h1_tc_lw", {
	pos = Vector(0, 123.7, 34),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-43, -119.42, 38.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("hummer_h1_tc_offroad_lw", {
	pos = Vector(0, 123.7, 34),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-43, -119.42, 38.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("jag_xfr", {
	pos = Vector(0, 119.7, 23),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -113.54, 41.5),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("jaguar_xj220", {
	pos = Vector(0, 122.7, 12),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -120.54, 21.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("lam_countach", {
	pos = Vector(0, 104.5, 17.5),
	ang = Angle(0, 180, 103),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -100.12, 26.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("lam_huracan_lw", {
	pos = Vector(0, 114.6, 13.5),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -99.8, 19),
	ang = Angle(0, 0, 70),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("lam_reventon_lw", {
	pos = Vector(8, 119, 13.5),
	ang = Angle(7, 163, 110),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -103.4, 30.4),
	ang = Angle(0, 0, 70),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("lancia_037_stradale_lw", {
	pos = Vector(0, -94.4, 18.4),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("lotus_esprit_80_lw", {
	pos = Vector(0, 113.6, 19.5),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -94.8, 34.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("lotus_exiges_roadster_lw", {
	pos = Vector(0, 98.6, 10.5),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -100.8, 29.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("miata94", {
	pos = Vector(0, 99.6, 18.5),
	ang = Angle(0, 180, 100),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -92.8, 32.5),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("mercedes_190e_evo_lw", {
	pos = Vector(0, -105.4, 31.4),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("mercedes_slk55_lw", {
	pos = Vector(0, 97.6, 21.5),
	ang = Angle(0, 180, 100),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -92.8, 36.9),
	ang = Angle(0, 0, 80),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("mer_g65_6x6", {
	pos = Vector(0, 124.7, 45),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -162.42, 40.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("merc_sprinter_boxtruck_lw", {
	pos = Vector(0, 179.3, 18),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -127.42, 20.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("merc_sprinter_lwb_lw", {
	pos = Vector(0.71, 134.7, 18.21),
	ang = Angle(0, 180, 100),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(-17.91, -156, 24.8),
	ang = Angle(0, -4, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("merc_sprinter_openchassis_lw", {
	pos = Vector(0.71, 179, 17),
	ang = Angle(0, 180, 100),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.84, -127.5, 21.2),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("merc_sprinter_swb_lw", {
	pos = Vector(0.71, 135, 17),
	ang = Angle(0, 180, 100),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(-17.91, -112, 24.8),
	ang = Angle(0, -4, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("evo6", {
	pos = Vector(-20, 107.6, 22.5),
	ang = Angle(0, 192, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -104, 42.7),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("morgan_3wheeler_lw", {
	pos = Vector(0, 68.6, 8.5),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -74, 20.7),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("nfsmustang", {
	pos = Vector(0, 130.6, 28.5),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -108, 32.7),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("nissan_silvia_s14_lw", {
	pos = Vector(0, 112.6, 20.5),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -113, 22),
	ang = Angle(0, 0, 93),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("nissan_silvia_s14_wide_lw", {
	pos = Vector(0, 113.6, 20.8),
	ang = Angle(0, 180, 80),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -110, 36),
	ang = Angle(0, 0, 76),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("nissan_silvia_s14_works_lw", {
	pos = Vector(0, 113.6, 20.8),
	ang = Angle(0, 180, 80),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -110, 34),
	ang = Angle(0, 0, 76),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("nissan_sileighty_lw", {
	pos = Vector(0, 107.9, 20.8),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -109.5, 20),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("nis_s13", {
	pos = Vector(0, 112.9, 20.8),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -109.5, 20),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("2000gtrstock", {
	pos = Vector(0, 101.9, 20.8),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -116.8, 30),
	ang = Angle(0, 0, 98),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("2000gtr_sh", {
	pos = Vector(0, 101.9, 20.8),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -116.8, 30),
	ang = Angle(0, 0, 98),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("nis_skyline_r32", {
	pos = Vector(0, 110.6, 23.8),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -110, 23),
	ang = Angle(0, 0, 104),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("smartfortwo", {
	pos = Vector(0, 67.62, 21.87),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -64.5, 43.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("subaru_impreza_2001_lw", {
	pos = Vector(0, 110, 20.8),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -106.2, 20),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("subaru_impreza_2004_lw", {
	pos = Vector(0, 108, 20.8),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -105.2, 22),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("yare_buggy", {
	pos = Vector(-12.5, -85.5, 40),
	ang = Angle(0, 0, 86),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("h1opentdm", {
	pos = Vector(35.25, -110, 35),
	ang = Angle(180, 180, -90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("jag_etypetdm", {
	pos = Vector(-0.07, -102.5, 24.68),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("jag_ftypetdm", {
	pos = Vector(0, 109.8, 20),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -106.6, 36.6),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("grandchetdm", {
	pos = Vector(0, 119.6, 31),
	ang = Angle(0, 180, 83),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -113.95, 51.9),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("jeewillystdm", {
	pos = Vector(-0.32, 75, 27.96),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(12.87, -86.85, 51.81),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("wranglertdm", {
	pos = Vector(0, 91, 32),
	ang = Angle(0, 180, 83),
	bg = {id = false, val = {}}
}, {
	pos = Vector(17, -84.95, 29.9),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("wrangler88tdm", {
	pos = Vector(0, 95, 28),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-29.8, -80.95, 38.1),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("wrangler_fnftdm", {
	pos = Vector(-0.25, 105.09, 43.9),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ceedtdm", {
	pos = Vector(-0.16, 107.29, 13.97),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.42, -96.5, 35.5),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("fortekouptdm", {
	pos = Vector(-0.09, 111, 20.25),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.92, -108.9, 25),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("xbowtdm", {
	pos = Vector(0.19, 92, 15.8),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.1, -82.4, 37.37),
	ang = Angle(0, 0, 70),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("diablotdm", {
	pos = Vector(-0.22, 112, 16.68),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(1.31, -109, 38.34),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("gallardotdm", {
	pos = Vector(0.21, 106, 20.12),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.4, -104.04, 32.31),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("gallardospydtdm", {
	pos = Vector(0.06, 105.53, 15.81),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.6, -107.04, 34.18),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("miuracontdm", {
	pos = Vector(0.03, 109.46, 20.78),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.6, -107.04, 34.18),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("miurap400tdm", {
	pos = Vector(0.03, 106.46, 20.78),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.6, -106.5, 30.18),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("murcielagotdm", {
	pos = Vector(0.71, 110.28, 15.96),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.54, -107.6, 30.93),
	ang = Angle(0, 0, 75),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("murcielagosvtdm", {
	pos = Vector(0.71, 116.28, 15.96),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.54, -107.9, 30.4),
	ang = Angle(0, 0, 75),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("reventonrtdm", {
	pos = Vector(0, 121.28, 15.96),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.32, -116.32, 33.2),
	ang = Angle(0, 0, 75),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("lrdefendertdm", {
	pos = Vector(0, 94.2, 42.2),
	ang = Angle(0, 180, 83),
	scale = 0.95,
	bg = {id = false, val = {}}
}, {
	pos = Vector(-14, -92.1, 56),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("landrovertdm", {
	pos = Vector(0, 117.8, 28),
	ang = Angle(0, 180, 95),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -116.2, 48),
	ang = Angle(0, 0, 87.4),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("landrover12tdm", {
	pos = Vector(0, 122.6, 28.8),
	ang = Angle(0, 180, 95),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -116.75, 50),
	ang = Angle(0, 0, 87.4),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("lex_is300tdm", {
	pos = Vector(0, 105.8, 23.8),
	ang = Angle(0, 180, 87.31),
	scale = 0.7,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -99.2, 38),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("lex_isftdm", {
	pos = Vector(0, 109.65, 13),
	ang = Angle(0, 180, 94),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -103.92, 39),
	ang = Angle(0, 0, 74),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("mas_ghiblitdm", {
	pos = Vector(-30.44, 109.71, 18.62),
	ang = Angle(0, 220, 87.4),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.03, -119.5, 40.56),
	ang = Angle(0, 0, 87.4),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("mas_quattrotdm", {
	pos = Vector(-34.5, 116.6, 24.62),
	ang = Angle(0, 210, 87.4),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.03, -121.5, 40.56),
	ang = Angle(0, 0, 87.4),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("furaitdm", {
	pos = Vector(-34.5, 103.6, 5),
	ang = Angle(0, 200, 0),
	bg = {id = false, val = {}}
}, {
	pos = Vector(23.37, -102, 25.5),
	ang = Angle(0, 0, 82.4),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("mx5tdm", {
	pos = Vector(-0.29, 97.5, 18.9),
	ang = Angle(0, 180, 87.4),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -91.32, 34.06),
	ang = Angle(0, 0, 82.4),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("rx7tdm", {
	pos = Vector(-0.29, 102.5, 16.9),
	ang = Angle(0, 180, 87.4),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.19, -102.1, 22.03),
	ang = Angle(0, 0, 82.4),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("rx8tdm", {
	pos = Vector(-0.41, 105.84, 18.06),
	ang = Angle(0, 180, 87.4),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.62, -105.85, 28.46),
	ang = Angle(0, 0, 82.4),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("speed3tdm", {
	pos = Vector(-0.41, 109.84, 18.06),
	ang = Angle(0, 180, 87.4),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.62, -107.85, 22.46),
	ang = Angle(0, 0, 82.4),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("mclarenf1tdm", {
	pos = Vector(0.06, 104.62, 14.5),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.13, -105.5, 20.18),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("mp412cgt3tdm", {
	pos = Vector(0.03, -107, 25),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("p1tdm", {
	pos = Vector(0, 115.21, 15),
	ang = Angle(0, 180, 94),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.03, -102.5, 18.75),
	ang = Angle(0, 0, 95.25),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("mer_slrtdm", {
	pos = Vector(-0.25, -108.72, 40.34),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("mer300seltdm", {
	pos = Vector(-0.07, 120.25, 15),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.1, -119.25, 28),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("c32amgtdm", {
	pos = Vector(-0.47, 112.75, 23.31),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -109.47, 39.71),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("mere63tdm", {
	pos = Vector(-0.1, 118, 20),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.21, -112.75, 39.5),
	ang = Angle(0, 0, 78),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("sl65amgtdm", {
	pos = Vector(-0.13, 113.75, 18.5),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.41, -99, 33.5),
	ang = Angle(0, 0, 73),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("slsamgtdm", {
	pos = Vector(0, 114.8, 16),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.5, -112, 24.25),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("cooper65tdm", {
	pos = Vector(0, 79, 15),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.5, -76, 30.62),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("clubmantdm", {
	pos = Vector(0, 92.5, 19),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.5, -90.75, 20),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("coopercoupetdm", {
	pos = Vector(0, 88, 19),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.5, -78, 36),
	ang = Angle(0, 0, 81),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("coopers11tdm", {
	pos = Vector(0, 88.5, 19),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.5, -81.5, 37.5),
	ang = Angle(0, 0, 75),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("cooper4x4tdm", {
	pos = Vector(0, 76.25, 44),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.5, -79, 58),
	ang = Angle(0, 0, 81),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("colttdm", {
	pos = Vector(0, 103, 25.46),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.5, -91.5, 28),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("morgaerosstdm", {
	pos = Vector(0.28, 92.2, 19),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.41, -100, 23.43),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("gtrtdm", {
	pos = Vector(0, 111.5, 22),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -110, 30.5),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("nis_leaftdm", {
	pos = Vector(0, 110.5, 21.15),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.06, -102, 22.5),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("noblem600tdm", {
	pos = Vector(0.84, 107.5, 13),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.31, -98.75, 25),
	ang = Angle(0, 0, 75),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("zondagrtdm", {
	pos = Vector(0, 107, 11),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-15.63, -105.5, 24.62),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("c12tdm", {
	pos = Vector(0, 102.5, 11),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(14.5, -101, 27),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("pon_fierogttdm", {
	pos = Vector(0.46, 101, 20.28),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.25, -96.32, 18.31),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("pon_firebirdtransamtdm", {
	pos = Vector(0.46, 124, 21.5),
	ang = Angle(0, 180, 90),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.25, -112, 34),
	ang = Angle(0, 0, 81),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("porgt3rsrtdm", {
	pos = Vector(0.06, 110, 17),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -107.5, 18.5),
	ang = Angle(0, -5, 90),
	scale = 0.7,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("918spydtdm", {
	pos = Vector(0.06, 114, 18.4),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -111.8, 29.5),
	ang = Angle(0, 0, 83),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("997gt3tdm", {
	pos = Vector(0.06, 106, 22),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -102, 26.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("carreragttdm", {
	pos = Vector(0.06, 110, 18),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -106.5, 23),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("cayenne12tdm", {
	pos = Vector(0.06, 119, 23),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -115, 45),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("cayennetdm", {
	pos = Vector(0.06, 113, 22),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -112, 41),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("sal_s281_00tdm", {
	pos = Vector(0.06, 109, 31),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -102, 47.5),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("sal_s281e_06tdm", {
	pos = Vector(0.06, 114, 24),
	ang = Angle(0, 180, 95),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -107.5, 43.5),
	ang = Angle(0, 0, 78),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("sal_s331_supercabtdm", {
	pos = Vector(0.06, 141.5, 30),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -139, 25.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("sciontctdm", {
	pos = Vector(0.62, 105.5, 20.5),
	ang = Angle(0, 180, 90),
	bg = {id = 7, val = {[2] = {pos = Vector(0.62, 106.26, 20.5), ang = Angle(0, 180, 90)}, [3] = {pos = Vector(0.62, 106.72, 20.5), ang = Angle(0, 180, 90)}}}
}, {
	pos = Vector(-0.66, -100, 36),
	ang = Angle(0, 0, 83),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("scionxdtdm", {
	pos = Vector(-0.29, 89.38, 23.56),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.04, -87.35, 37.06),
	ang = Angle(0, 0, 83),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("she1000tdm", {
	pos = Vector(0, 116, 30),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -113.16, 36.88),
	ang = Angle(0.24, 0.06, 82.26),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vipvipertdm", {
	pos = Vector(0, 108, 18),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -106, 36),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("subimpreza08tdm", {
	pos = Vector(0, 106, 18),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -101.5, 39),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("subimpreza05tdm", {
	pos = Vector(0, 106, 19),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -105, 23.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("subleggt10tdm", {
	pos = Vector(0, 114, 17),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -109.4, 37.7),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("sublegrs90tdm", {
	pos = Vector(0, -108, 22.5),
	ang = Angle(0, 0, 76),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("tesmodelstdm", {
	pos = Vector(0, -122, 38.5),
	ang = Angle(0, 0, 76),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("toyfjtdm", {
	pos = Vector(0, 112, 35),
	ang = Angle(0, 180, 94),
	scale = 1.2,
	bg = {id = false, val = {}}
}, {
	pos = Vector(24, -96.28, 42.9),
	ang = Angle(0, 4, 85),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("mr2gttdm", {
	pos = Vector(0, 98, 15.4),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -97.1, 22.3),
	ang = Angle(0, 0, 86),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("priustdm", {
	pos = Vector(0, 105.7, 24.7),
	ang = Angle(0, 180, 80),
	scale = 0.85,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -98.95, 39),
	ang = Angle(0, 0, 75.5),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("toyrav4tdm", {
	pos = Vector(0, 104.1, 31.5),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-22, -94.15, 33),
	ang = Angle(0, -1.2, 93),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("supratdm", {
	pos = Vector(0, 103.85, 21.68),
	ang = Angle(0, 180, 90),
	scale = 0.73,
	bg = {id = 3, val = {[0] = {pos = Vector(0, 107.24, 19.51), ang = Angle(0, 180, 90), scale = 0.73}, [1] = {pos = Vector(0, 107.57, 20.88), ang = Angle(0, 180, 90), scale = 0.73}, [2] = {pos = Vector(0, 107.47, 22.25), ang = Angle(0, 180, 90), scale = 0.73}, [3] = {pos = Vector(0, 106.1, 20.78), ang = Angle(0, 180, 90), scale = 0.73}, [4] = {pos = Vector(0, 107.36, 22.57), ang = Angle(0, 180, 90), scale = 0.73}, [5] = {pos = Vector(0, 107.5, 20.8), ang = Angle(0, 180, 90), scale = 0.73}, [6] = {pos = Vector(0, 107.46, 19.57), ang = Angle(0, 180, 90), scale = 0.73}}}
}, {
	pos = Vector(0, -104.7, 29.5),
	ang = Angle(0, 0, 90),
	bg = {id = 4, val = {[1] = {pos = Vector(0, -105.8, 29.5), ang = Angle(0, 0, 90)}, [3] = {pos = Vector(0, -105.49, 30.12), ang = Angle(0, 0, 90)}}}
})

PLATE:RegisterPlate("toytundratdm", {
	pos = Vector(0, 142.6, 35),
	ang = Angle(0, 180, 104.58),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -136.65, 41.3),
	ang = Angle(0, 0, 95.8),
	scale = 0.9,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vauxagilatdm", {
	pos = Vector(0, 89.47, 24.7),
	ang = Angle(0, 180, 85),
	scale = 0.85,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -86.6, 26.5),
	ang = Angle(0, 0, 78),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vauxastra12tdm", {
	pos = Vector(0, 108.99, 23.33),
	ang = Angle(0, 180, 85.64),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -102.35, 28.5),
	ang = Angle(0, 0, 78.4),
	scale = 0.85,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vauxcorsatdm", {
	pos = Vector(0, 93.7, 23.47),
	ang = Angle(0, 180, 94.75),
	scale = 0.95,
	bg = {id = 3, val = {[0] = {pos = Vector(0, 93.9, 27.12), ang = Angle(0, 180, 79.12), scale = 0.95}}}
}, {
	pos = Vector(0, -91.48, 27.5),
	ang = Angle(0, 0, 65),
	scale = 0.85,
	bg = {id = 4, val = {[1] = {pos = Vector(0, -91.71, 25.83), ang = Angle(0, 0, 68.24), scale = 0.85}}}
})

PLATE:RegisterPlate("vauxinsigniatdm", {
	pos = Vector(0, 115.19, 24.8),
	ang = Angle(0, 180, 90),
	scale = 0.75,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -115.85, 32),
	ang = Angle(0, 0, 74.5),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("beetle68tdm", {
	pos = Vector(0, 94.38, 20.6),
	ang = Angle(0, 180, 92.8),
	bg = {id = 3, val = {[0] = {pos = Vector(22.08, 85.96, 16.33), ang = Angle(0.21, 172.53, 69.84)}, [2] = {pos = Vector(21.97, 85.84, 16.1), ang = Angle(0, 172.24, 74.01)}}}
}, {
	pos = Vector(0, -91.73, 29),
	ang = Angle(0, 0, 56.2),
	scale = 0.87,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vwcampertdm", {
	pos = Vector(0, 114.2, 25),
	ang = Angle(0, 180, 90),
	scale = 1.3,
	bg = {id = 4, val = {[2] = {pos = Vector(0, 110.34, 25), ang = Angle(0, 180, 90), scale = 1.3}, [3] = {pos = Vector(0, 110.5, 25), ang = Angle(0, 180, 90), scale = 1.3}}}
}, {
	pos = Vector(0, -99.71, 36),
	ang = Angle(0, 0, 81.9),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vwgolfgti14tdm", {
	pos = Vector(0, 103.17, 22.25),
	ang = Angle(0, 180, 90),
	scale = 0.7,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -100.9, 22),
	ang = Angle(0, 0, 80),
	scale = 0.9,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("golfmk2tdm", {
	pos = Vector(0, 95.8, 22.99),
	ang = Angle(0, 180, 90),
	scale = 0.7,
	bg = {id = 3, val = {[0] = {pos = Vector(0, 96.58, 23.47), ang = Angle(0, 180, 90), scale = 0.7}, [2] = {pos = Vector(0, 96.8, 23.94), ang = Angle(0, 180, 87.63), scale = 0.7}, [3] = {pos = Vector(0, 95.81, 22.99), ang = Angle(0, 180, 90), scale = 0.7}}}
}, {
	pos = Vector(0, -90.15, 42.67),
	ang = Angle(0, 0, 71.45),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vw_golfr32tdm", {
	pos = Vector(0, 96.96, 24.1),
	ang = Angle(0, 180, 90),
	scale = 0.78,
	bg = {id = 3, val = {[3] = {pos = Vector(0, 96.65, 24.83), ang = Angle(0, 180, 88.57), scale = 0.78}, [4] = {pos = Vector(0, 98.19, 24.1), ang = Angle(0, 180, 89.12), scale = 0.78}, [5] = {pos = Vector(0, 97.55, 22.72), ang = Angle(0, 180, 90), scale = 0.78}}}
}, {
	pos = Vector(0, -96.55, 24),
	ang = Angle(0, 0, 75),
	bg = {id = 4, val = {[2] = {pos = Vector(0, -96.85, 24.89), ang = Angle(0, 0, 72.77)}, [3] = {pos = Vector(0, -96.54, 24.49), ang = Angle(0, 0, 72.79)}, [4] = {pos = Vector(0, -97.27, 24.47), ang = Angle(0, 0, 86.42)}, [5] = {pos = Vector(0, -96.46, 24.48), ang = Angle(0, 0, 89.39)}}}
})

PLATE:RegisterPlate("golfvr6tdm", {
	pos = Vector(0, 100.44, 19.9),
	ang = Angle(0, 180, 90),
	scale = 0.84,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -89.1, 37.5),
	ang = Angle(0, 0, 77.5),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vwbeetleconvtdm", {
	pos = Vector(0, 103.69, 22),
	ang = Angle(0, 180, 83),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -96.1, 23.3),
	ang = Angle(0, 0, 70.2),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vwsciroccortdm", {
	pos = Vector(0, 98.4, 17.8),
	ang = Angle(0, 180, 88.5),
	scale = 0.85,
	bg = {id = 3, val = {[0] = {pos = Vector(0, 98.71, 22.11), ang = Angle(0, 180, 88.5), scale = 0.85}, [1] = {pos = Vector(0, 98.6, 21.79), ang = Angle(0, 180, 88.5), scale = 0.85}, [2] = {pos = Vector(0, 97.15, 23.77), ang = Angle(0.14, 180, 92.85), scale = 0.85}, [3] = {pos = Vector(0, 97.47, 23.83), ang = Angle(0, 180, 89.08), scale = 0.85}, [4] = {pos = Vector(0, 98.71, 21.98), ang = Angle(0, 180, 88.5), scale = 0.85}}}
}, {
	pos = Vector(0, -96.66, 27),
	ang = Angle(0, 0, 75),
	bg = {id = 4, val = {[1] = {pos = Vector(0, -97.07, 27), ang = Angle(0, 0, 75)}, [2] = {pos = Vector(0, -95.93, 27), ang = Angle(0, 0, 80.28), scale = 1}}}
})

PLATE:RegisterPlate("242turbotdm", {
	pos = Vector(0, 122.45, 17.3),
	ang = Angle(0, 180, 100),
	scale = 0.75,
	bg = {id = 3, val = {[2] = {pos = Vector(0, 117.72, 17.3), ang = Angle(0, 180, 100), scale = 0.75}}}
}, {
	pos = Vector(0, -106.3, 28),
	ang = Angle(0, 0, 78),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vol850rtdm", {
	pos = Vector(0, 116.4, 19.9),
	ang = Angle(0, 180, 95),
	scale = 0.78,
	bg = {id = 3, val = {[0] = {pos = Vector(0, 116.64, 19.9), ang = Angle(0, 180, 95), scale = 0.78}, [2] = {pos = Vector(0, 117, 19.9), ang = Angle(0, 180, 95), scale = 0.78}}}
}, {
	pos = Vector(0, -110, 36),
	ang = Angle(0, 0, 84.9),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vols60tdm", {
	pos = Vector(0, 109.65, 14.7),
	ang = Angle(0, 180, 91),
	scale = 0.7,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -105.45, 36),
	ang = Angle(0, 0, 83.5),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("volxc70tdm", {
	pos = Vector(0, 118.5, 17.6),
	ang = Angle(0, 180, 91),
	scale = 0.7,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -110.9, 34),
	ang = Angle(0, 0, 79.6),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("volxc90tdm", {
	pos = Vector(0, 116.78, 18.7),
	ang = Angle(0, 180, 104.58),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -113.19, 46),
	ang = Angle(0, 0, 91),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("st1tdm", {
	pos = Vector(0, 111.19, 15),
	ang = Angle(0, 180, 87.31),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -113.32, 22.5),
	ang = Angle(0, 0, 76.5),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("sm_12bmw530dtouremer", {
	pos = Vector(0, 121, 23),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -118, 38.4),
	ang = Angle(0, 0, 75),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("sm_14bmw530dtouremer", {
	pos = Vector(0, 121, 23),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -118, 38.4),
	ang = Angle(0, 0, 75),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("sm_charpursuit15", {
	pos = Vector(0, 118.59, 24),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -126.8, 30),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("rv", {
	pos = Vector(-0.63, 169.59, 18.81),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(30.96, -160.07, 18.84),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("17raptor_cop_sgm", {
	pos = Vector(0.03, 130.81, 29.59),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.09, -118.63, 35.31),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("demon_sgm", {
	pos = Vector(-0.25, 121.87, 16.09),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.21, -123.16, 25.78),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bus", {
	pos = Vector(-0.72, 172.09, 28.28),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.16, -233.44, 33),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("models_sgm", {
	pos = Vector(-0.19, 117.96, 14.65),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.09, -122.16, 36),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("smc_bui_regal_gnx", {
	pos = Vector(0, 118.9, 22),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -114.5, 37.5),
	ang = Angle(0, 0, 75),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("smc_bel_air", {
	pos = Vector(0, 114.95, 17.5),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -128.9, 21),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("smc_che_cam_irocz", {
	pos = Vector(0, 114.9, 20),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -108.5, 37),
	ang = Angle(0, 0, 75),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("smc_ss396", {
	pos = Vector(0, 104.5, 17.5),
	ang = Angle(0, 180, 108),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -130.6, 25),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("smc_corvettezr1_19", {
	pos = Vector(0, 112.5, 17.5),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -109, 23.5),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("smc_chevyii_nova", {
	pos = Vector(0, 106.2, 20),
	ang = Angle(0, 180, 105),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -114.3, 27),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("smc_mustang_gt_15", {
	pos = Vector(0, 111.95, 22),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -119.9, 28.9),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("smc_maz_rx7_gslse", {
	pos = Vector(0, 104.8, 22),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -102, 20),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("smc_olds_hurst", {
	pos = Vector(0, 117, 22),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -125, 22.3),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("smc_ply_cuda426", {
	pos = Vector(0, 108, 18),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -112, 38),
	ang = Angle(0, 0, 75),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("smc_ply_roadrunner", {
	pos = Vector(0, 122.5, 21),
	ang = Angle(0, 180, 107),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -119.9, 20.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("smc_pon_firebird_68", {
	pos = Vector(0, 106.65, 19.5),
	ang = Angle(0, 180, 107),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -112.7, 24),
	ang = Angle(0, 0, 95),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("smc_pon_g8_gxp", {
	pos = Vector(0, 121.6, 21),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -115, 42),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("smc_pon_gto_judge", {
	pos = Vector(0, 114.5, 19),
	ang = Angle(0, 180, 102),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -122.5, 25.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("smc_cobra427", {
	pos = Vector(0, 91.2, 12.3),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -92.67, 25.5),
	ang = Angle(0, 0, 88),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("smc_toy_gt86rb", {
	pos = Vector(0, 106.1, 19),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -98.5, 35),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("alfa_stradaletdm", {
	pos = Vector(0, 89.4, 24.8),
	ang = Angle(0, 180, 30),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -93.45, 31.2),
	ang = Angle(0, 0, 101),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("alfa_giuliettatdm", {
	pos = Vector(-19.29, 102.5, 25.2),
	ang = Angle(0, 193.5, 82),
	scale = 0.7,
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.91, -100.9, 26.7),
	ang = Angle(0, 0, 76),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ast_db5tdm", {
	pos = Vector(0, 111.5, 20),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -106.6, 31.2),
	ang = Angle(0, 0, 85),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("dbstdm", {
	pos = Vector(0, 113, 20),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -107, 40),
	ang = Angle(0, 0, 75),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ast_rapidetdm", {
	pos = Vector(0, 122.75, 21.5),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.29, -118.7, 30.55),
	ang = Angle(0, 0, 73),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("v12vantagetdm", {
	pos = Vector(0, 104.9, 16),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.29, -109.8, 24.6),
	ang = Angle(0, 0, 78),
	scale = 0.9,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("audir8tdm", {
	pos = Vector(0, 107.9, 21.5),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -103.5, 29.2),
	ang = Angle(0, 0, 70),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("audir8spydtdm", {
	pos = Vector(0, 109, 27),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -103.2, 35.9),
	ang = Angle(0, 0, 70),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("audir8plustdm", {
	pos = Vector(0, 107, 24),
	ang = Angle(0, 180, 81),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -102, 34),
	ang = Angle(0, 0, 70),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("rs4avanttdm", {
	pos = Vector(0, 108.6, 22),
	ang = Angle(0, 180, 85),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -110.5, 34.5),
	ang = Angle(0, 0, 76),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("auds4tdm", {
	pos = Vector(0, 106.5, 24),
	ang = Angle(0, 180, 85),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -109.3, 38),
	ang = Angle(0, 0, 76),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("auds5tdm", {
	pos = Vector(0, 106.5, 24),
	ang = Angle(0, 180, 85),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -109.3, 38),
	ang = Angle(0, 0, 76),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("auditttdm", {
	pos = Vector(2.5, 101.5, 20.5),
	ang = Angle(0, 180, 80),
	bg = {id = false, val = {}}
}, {
	pos = Vector(2.8, -94, 29.9),
	ang = Angle(0, 0, 65),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bmw1mtdm", {
	pos = Vector(0, 103.5, 20),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -99, 38.5),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bmw_340itdm", {
	pos = Vector(0.28, 113.9, 20.9),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.69, -108, 39),
	ang = Angle(0, 0, 70),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("507tdm", {
	pos = Vector(-0.1, 108, 28.5),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -105, 27.81),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bmw_isettatdm", {
	pos = Vector(0, 54.5, 18),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -48, 18),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("m1tdm", {
	pos = Vector(0, 104, 12),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -103, 34.5),
	ang = Angle(0, 0, 70),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("m3e92tdm", {
	pos = Vector(0, 111, 16),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -106, 32),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bmwm3gtrtdm", {
	pos = Vector(0, 110, 24.12),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.21, -102.2, 39.4),
	ang = Angle(0, 0, 78),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("m5e34tdm", {
	pos = Vector(0, 115.3, 21),
	ang = Angle(0, 180, 90),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -111, 39),
	ang = Angle(0, 0, 90),
	scale = 0.9,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bmwm5e60tdm", {
	pos = Vector(0, 116.06, 26.62),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -108, 41),
	ang = Angle(0, 0, 75),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bmwm613tdm", {
	pos = Vector(0, 118.28, 32),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -117.5, 33),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bowlexrstdm", {
	pos = Vector(0, 102.62, 21.5),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -101.5, 45),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("eb110tdm", {
	pos = Vector(0.12, 108, 13.5),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -105, 33),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("veyrontdm", {
	pos = Vector(0, -108, 30.5),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("veyronsstdm", {
	pos = Vector(0, -94.7, 30.7),
	ang = Angle(0, 0, 83),
	scale = 0.7,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("cad_escaladetdm", {
	pos = Vector(0, 123.5, 27.5),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -124.5, 44.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("cad_lmptdm", {
	pos = Vector(18, 103, 17.2),
	ang = Angle(0, 180, 25),
	scale = 0.5,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("che_blazertdm", {
	pos = Vector(0, 106.5, 22),
	ang = Angle(0, 180, 105),
	scale = 0.7,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -105.8, 26.7),
	ang = Angle(0, 0, 90),
	scale = 0.9,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("che_c10tdm", {
	pos = Vector(0, 116.5, 21.9),
	ang = Angle(0, 180, 95),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -108.45, 23.4),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("che_69camarotdm", {
	pos = Vector(0, 116.3, 19),
	ang = Angle(0, 180, 100),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -103.47, 25.4),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("che_camarozl1tdm", {
	pos = Vector(0, 115, 23.21),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -112, 33.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("che_chevellesstdm", {
	pos = Vector(0, 124, 19),
	ang = Angle(0, 180, 100),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -120.9, 25.8),
	ang = Angle(0, 0, 90),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("che_corv_gsctdm", {
	pos = Vector(0, 111.8, 21),
	ang = Angle(0, 180, 100),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -103.5, 29.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("che_stingray427tdm", {
	pos = Vector(0.53, 103.8, 24),
	ang = Angle(0, 180, 115),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -104, 26),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("che_impala96tdm", {
	pos = Vector(0, 121, 17),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -140, 35),
	ang = Angle(0, 0, 70),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("che_sparktdm", {
	pos = Vector(0, 88.25, 20),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -85.5, 39),
	ang = Angle(0, 0, 70),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("300ctdm", {
	pos = Vector(0, 124, 21),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -124, 29.5),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("chr300c12tdm", {
	pos = Vector(0, 121, 21),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -119, 29.5),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ptcruisertdm", {
	pos = Vector(0, 105, 19),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -102, 20.5),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("citroenc1tdm", {
	pos = Vector(0, 85, 22.5),
	ang = Angle(0, 180, 90),
	scale = 0.9,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -81, 18.6),
	ang = Angle(0, 0, 85),
	scale = 0.9,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("c4tdm", {
	pos = Vector(0, 96, 21),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -99.4, 25.7),
	ang = Angle(0, 0, 83),
	scale = 0.9,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("deloreantdm", {
	pos = Vector(0, 102, 22),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.25, -100.7, 40.8),
	ang = Angle(0, 0, 80),
	scale = 0.9,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("challenger70tdm", {
	pos = Vector(0, 114, 21),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -117, 27),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("dod_challenger15tdm", {
	pos = Vector(0, 122, 22.2),
	ang = Angle(0, 180, 115),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -121.5, 27.3),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("chargersrt8tdm", {
	pos = Vector(0, 121.8, 23),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -118.8, 29),
	ang = Angle(0, 0, 85),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("charger2012tdm", {
	pos = Vector(0, 121.8, 23),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -126, 31),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("dod_ram_1500tdm", {
	pos = Vector(0, 126, 23.5),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-26, -132.6, 28),
	ang = Angle(0, -4, 97),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("dod_ram_3500tdm", {
	pos = Vector(0, 147.2, -19),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -149.8, -9.2),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("fer_250gtotdm", {
	pos = Vector(0, 102.37, 19.75),
	ang = Angle(0, 180, 40),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -101.2, 23.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("fer_250gttdm", {
	pos = Vector(0, 102.6, 18),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -102.7, 20.68),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("fer_458spidtdm", {
	pos = Vector(0, 109, 13.9),
	ang = Angle(0, 180, 90),
	scale = 0.9,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -110, 29),
	ang = Angle(0, 0, 70),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("fer_512trtdm", {
	pos = Vector(0, 109.2, 13.4),
	ang = Angle(0, 180, 100),
	scale = 0.9,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -107, 21.5),
	ang = Angle(0, 0, 90),
	scale = 0.9,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("fer_enzotdm", {
	pos = Vector(1.2, 115.8, 16.4),
	ang = Angle(0, 180, 90),
	scale = 0.7,
	bg = {id = false, val = {}}
}, {
	pos = Vector(1.1, -114, 27),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ferf12tdm", {
	pos = Vector(0, 109.5, 18),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -108.9, 33.2),
	ang = Angle(0, 0, 80),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ferf430tdm", {
	pos = Vector(0, 107.2, 14.5),
	ang = Angle(0, 180, 140),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -106, 27.4),
	ang = Angle(0, 0, 77),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("fer_f50tdm", {
	pos = Vector(0.81, 111, 9.84),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.25, -109, 20.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("fer_lafertdm", {
	pos = Vector(-13.5, 112, 17.31),
	ang = Angle(0, 195, 95),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-16.19, -100, 31.71),
	ang = Angle(0, -10, 77),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("crownvic_taxitdm", {
	pos = Vector(-0.2, 137.34, 20.46),
	ang = Angle(0, 180, 102),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.2, -112.29, 37.91),
	ang = Angle(0, 0, 84),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("coupe40tdm", {
	pos = Vector(-22.94, 109.65, 17.75),
	ang = Angle(0, 194, 95),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.06, -113.6, 22.59),
	ang = Angle(0, 0, 84),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("f100tdm", {
	pos = Vector(-35.38, 116.65, 19.18),
	ang = Angle(0, 186, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.06, -113.6, 22.59),
	ang = Angle(0, 0, 84),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("f350tdm", {
	pos = Vector(0.18, 134.21, 33.68),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.19, -155.97, 35.28),
	ang = Angle(0, 0, 84),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("focusrstdm", {
	pos = Vector(0, 100.95, 22.25),
	ang = Angle(0, 180, 87),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.15, -103.22, 37.5),
	ang = Angle(0, 0, 82),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("for_focus_rs16tdm", {
	pos = Vector(0, 102.95, 18.25),
	ang = Angle(0, 180, 87),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.15, -100.8, 46.5),
	ang = Angle(0, 0, 75),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("focussvttdm", {
	pos = Vector(-0.07, 102.73, 17.21),
	ang = Angle(0, 180, 85),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.15, -98.42, 41.5),
	ang = Angle(0, 0, 82),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("gt05tdm", {
	pos = Vector(-0.07, 105.73, 17.21),
	ang = Angle(0, 180, 102),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.81, -107.5, 32.78),
	ang = Angle(0, 0, 107),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("mustanggttdm", {
	pos = Vector(0.56, 115.8, 25.28),
	ang = Angle(0, 180, 102),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.35, -114.29, 26.62),
	ang = Angle(0, 0, 93),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("raptorsvttdm", {
	pos = Vector(0, 136.5, 27.3),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -126.9, 32.9),
	ang = Angle(0, 0, 89),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("for_she_gt500tdm", {
	pos = Vector(0.56, 113.6, 20.28),
	ang = Angle(0, 180, 102),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.06, -112.75, 33.34),
	ang = Angle(0, 0, 93),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("transittdm", {
	pos = Vector(0.56, 121.5, 25.28),
	ang = Angle(0, 180, 102),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.06, -112.75, 40.34),
	ang = Angle(0, 0, 93),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("sierralowtdm", {
	pos = Vector(0, 125, 22.5),
	ang = Angle(0, 180, 90),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -128.5, 27.4),
	ang = Angle(0, 0, 90),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("sierratdm", {
	pos = Vector(0, 125, 42.5),
	ang = Angle(0, 180, 90),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -128.5, 47.4),
	ang = Angle(0, 0, 90),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("syclonetdm", {
	pos = Vector(0.28, 113, 22.93),
	ang = Angle(0, 180, 90),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.46, -107.2, 23.87),
	ang = Angle(0, 0, 90),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("gmcvantdm", {
	pos = Vector(0, 113.5, 20.5),
	ang = Angle(0, 180, 100),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.8, -110.9, 19.25),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("hsvgtstdm", {
	pos = Vector(0.31, 121.5, 23.71),
	ang = Angle(0, 180, 90),
	scale = 0.9,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.93, -117.16, 42.43),
	ang = Angle(0, 0, 90),
	scale = 0.9,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("hsvw427tdm", {
	pos = Vector(0.31, 123, 23.71),
	ang = Angle(0, 180, 90),
	scale = 0.9,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.93, -115.5, 42.43),
	ang = Angle(0, 0, 90),
	scale = 0.9,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("civictypertdm", {
	pos = Vector(0.31, 108.5, 21.71),
	ang = Angle(0, 180, 90),
	scale = 0.9,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -94, 38.5),
	ang = Angle(0, 0, 80),
	scale = 0.9,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("civic97tdm", {
	pos = Vector(0.31, 103.5, 22.71),
	ang = Angle(0, 180, 90),
	scale = 0.9,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -96.5, 40),
	ang = Angle(0, 0, 80),
	scale = 0.9,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("hudhornettdm", {
	pos = Vector(-0.44, 130, 24.62),
	ang = Angle(0, 180, 90),
	scale = 0.9,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.12, -127.88, 23),
	ang = Angle(0, 0, 80),
	scale = 0.9,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("courier_trucktdm", {
	pos = Vector(0, 139.6, 31.6),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-39, -150, 110),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bustdm", {
	pos = Vector(0, 263.5, 60),
	ang = Angle(0, 180, 90),
	scale = 1.3,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -267.5, 68),
	ang = Angle(0, 0, 90),
	scale = 1.3,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("charger12poltdm", {
	pos = Vector(0, 120.11, 22.8),
	ang = Angle(0, 180, 95),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -125.85, 30.8),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("chargersrt8poltdm", {
	pos = Vector(7, 120.65, 22.5),
	ang = Angle(0, 171.2, 98),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -118.7, 28.8),
	ang = Angle(0, 0, 90),
	scale = 0.81,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("forcrownvicpoltdm", {
	pos = Vector(0, 125.9, 22),
	ang = Angle(0, 180, 112),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -123.5, 38),
	ang = Angle(0, 0, 79),
	scale = 0.9,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("for_crownvic_fh3tdm", {
	pos = Vector(0, 121.95, 24.8),
	ang = Angle(0, 180, 97),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -127.9, 43.5),
	ang = Angle(0, 0, 79),
	scale = 0.9,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("fortauruspoltdm", {
	pos = Vector(0, 123.5, 19),
	ang = Angle(0, 180, 97),
	scale = 0.9,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -123.5, 26),
	ang = Angle(0, 0, 90),
	scale = 0.87,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("hsvw427poltdm", {
	pos = Vector(0, 121.9, 16.5),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -114.95, 43),
	ang = Angle(0, 0, 79),
	scale = 0.87,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("lex_is300poltdm", {
	pos = Vector(0, 105.8, 23.8),
	ang = Angle(0, 180, 87.31),
	scale = 0.7,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -99.2, 38),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("mereclasspoltdm", {
	pos = Vector(0, 103, 17.7),
	ang = Angle(0, 180, 100),
	scale = 0.73,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -120.25, 41.5),
	ang = Angle(0, 0, 83),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("mitsuevoxpoltdm", {
	pos = Vector(0, 105.25, 21.5),
	ang = Angle(0, 180, 99),
	scale = 0.9,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -105.3, 42),
	ang = Angle(0, 0, 95),
	scale = 0.87,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("scaniafiretdm", {
	pos = Vector(0, 149, 37.5),
	ang = Angle(0, 180, 90),
	scale = 1.1,
	bg = {id = false, val = {}}
}, {
	pos = Vector(30, -163.9, 40),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("airtugtdm", {
	pos = Vector(0, 61, 18.5),
	ang = Angle(0, 180, 90),
	scale = 0.85,
	bg = {id = false, val = {}}
}, {
	pos = Vector(17, -47.38, 20),
	ang = Angle(0, 0, 79),
	scale = 0.85,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("fgtargsytdm", {
	pos = Vector(0, 123.4, 30.9),
	ang = Angle(180, 0, -84),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -3, 130),
	ang = Angle(0, 0, 90),
	scale = 1.3,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("c5500tdm", {
	pos = Vector(0, 124.62, 23.5),
	ang = Angle(180, 0, -85),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -208.35, 19.58),
	ang = Angle(0, 0, 90),
	scale = 0.78,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("kwt800tdm", {
	pos = Vector(0, 182.59, 30),
	ang = Angle(0, 180, 90),
	scale = 1.2,
	bg = {id = false, val = {}}
}, {
	pos = Vector(-36, -9.2, 98),
	ang = Angle(0, 0, 90),
	scale = 1.2,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("peterbilt_579tdm", {
	pos = Vector(0, 173.75, 41.5),
	ang = Angle(180, 0, -94.9),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -123.39, 48),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("peterbilt_579medtdm", {
	pos = Vector(0, 173.75, 47.5),
	ang = Angle(180, 0, -94.9),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -174.83, 54),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("f150tal1981", {
	pos = Vector(0, 118.5, 30.5),
	ang = Angle(0, 180, 95),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.2, -142.3, 29.2),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("tal86silverado_2500", {
	pos = Vector(0, 129.5, 25),
	ang = Angle(0, 180, 108),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.2, -128.5, 28),
	ang = Angle(0, 0, 90),
	scale = 0.85,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("tal86silverado_2500cc", {
	pos = Vector(0, 129.5, 25),
	ang = Angle(0, 180, 108),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.2, -169, 28),
	ang = Angle(0, 0, 90),
	scale = 0.85,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("tal86silverado", {
	pos = Vector(0, 129.5, 25),
	ang = Angle(0, 180, 108),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.2, -169, 28),
	ang = Angle(0, 0, 90),
	scale = 0.85,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("tal86suburban353", {
	pos = Vector(0, 102, 26.5),
	ang = Angle(0, 180, 108),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.2, -144.5, 26),
	ang = Angle(0, 0, 90),
	scale = 0.85,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("tal86suburban379", {
	pos = Vector(0, 102, 26.5),
	ang = Angle(0, 180, 108),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.2, -144.5, 26),
	ang = Angle(0, 0, 90),
	scale = 0.85,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("tal86suburban440", {
	pos = Vector(0, 102, 26.5),
	ang = Angle(0, 180, 108),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.2, -144.5, 26),
	ang = Angle(0, 0, 90),
	scale = 0.85,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("tal86suburban454", {
	pos = Vector(0, 102, 26.5),
	ang = Angle(0, 180, 108),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-0.2, -144.5, 26),
	ang = Angle(0, 0, 90),
	scale = 0.85,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("talblazer", {
	pos = Vector(0, 129.2, 25.5),
	ang = Angle(0, 180, 108),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -95, 26),
	ang = Angle(0, 0, 90),
	scale = 0.85,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("tal89suburban", {
	pos = Vector(-1.3, 123.9, 30),
	ang = Angle(0, 180, 108),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-1.79, -125, 29.5),
	ang = Angle(0, 0, 90),
	scale = 0.85,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("talsilveradotc", {
	pos = Vector(0, 153, 27.8),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -135.6, 27),
	ang = Angle(0, 0, 90),
	scale = 0.85,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("silverado2500hdtal", {
	pos = Vector(0, 160, 27.8),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-1, -128, 25.3),
	ang = Angle(0, 0, 90),
	scale = 0.75,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("silverado2500hdtal_d", {
	pos = Vector(0, 160, 27.8),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-1, -128, 25.3),
	ang = Angle(0, 0, 90),
	scale = 0.75,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("talsuburban2015", {
	pos = Vector(0, 140, 30),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -128, 47),
	ang = Angle(0, 0, 90),
	scale = 0.85,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("f150tal", {
	pos = Vector(1.3, 126.5, 25),
	ang = Angle(0, 180, 90),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.7, -139.5, 28.5),
	ang = Angle(0, 0, 96),
	scale = 0.75,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("f150poltal", {
	pos = Vector(1.3, 126.5, 25),
	ang = Angle(0, 180, 90),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.7, -139.5, 28.5),
	ang = Angle(0, 0, 96),
	scale = 0.75,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("taltigr", {
	pos = Vector(-18.35, -103.69, 55.68),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("h2talstock", {
	pos = Vector(0.2, 124, 32),
	ang = Angle(0, 180, 87),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -94, 51),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("talh3", {
	pos = Vector(0.2, 89, 30.5),
	ang = Angle(0, 180, 130),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -94, 51),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("talh3alpha", {
	pos = Vector(0.2, 89, 30.5),
	ang = Angle(0, 180, 130),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -94, 51),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("tallm002", {
	pos = Vector(0, 108, 31.4),
	ang = Angle(0, 180, 95),
	scale = 0.9,
	bg = {id = false, val = {}}
}, {
	pos = Vector(-33, -111.8, 60),
	ang = Angle(0, 0, 80),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("humveetal733", {
	pos = Vector(-0.38, 105, 46),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -105, 50.71),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("mrapcougartal733", {
	pos = Vector(42.5, -115, 40),
	ang = Angle(0, 0, 90),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("maxxprotal", {
	pos = Vector(-2.5, -111, 57),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("matvtal733", {
	pos = Vector(34.5, -115, 97),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("bmw_530d_touring_pol_lw", {
	pos = Vector(0, 118.06, 20.95),
	ang = Angle(0, 180, 90),
	scale = 0.804,
	bg = {id = 7, val = {[2] = {pos = Vector(0, 117.02, 20.57), ang = Angle(0, 180, 90), scale = 0.804}, [3] = {pos = Vector(0, 117.02, 20.52), ang = Angle(0, 180, 90), scale = 0.804}, [4] = {pos = Vector(0, 116.6, 21.05), ang = Angle(0, 180, 98.05), scale = 0.671}}}
}, {
	pos = Vector(0, -114.91, 36.01),
	ang = Angle(0, 0, 76.46),
	scale = 0.774,
	bg = {id = 7, val = {[4] = {pos = Vector(0, -114.31, 36.01), ang = Angle(0, 0, 73.9), scale = 0.97}}}
})

PLATE:RegisterPlate("bmw_530d_touring_und_lw", {
	pos = Vector(0, 118.06, 20.95),
	ang = Angle(0, 180, 90),
	scale = 0.804,
	bg = {id = 7, val = {[2] = {pos = Vector(0, 117.02, 20.57), ang = Angle(0, 180, 90), scale = 0.804}, [3] = {pos = Vector(0, 117.02, 20.52), ang = Angle(0, 180, 90), scale = 0.804}, [4] = {pos = Vector(0, 116.6, 21.05), ang = Angle(0, 180, 98.05), scale = 0.671}}}
}, {
	pos = Vector(0, -114.91, 36.01),
	ang = Angle(0, 0, 76.46),
	scale = 0.774,
	bg = {id = 7, val = {[4] = {pos = Vector(0, -114.31, 36.01), ang = Angle(0, 0, 73.9), scale = 0.97}}}
})

PLATE:RegisterPlate("bmw_x5_48i_pol_lw", {
	pos = Vector(0, 122.18, 25.56),
	ang = Angle(0, 180, 90),
	scale = 0.786,
	bg = {id = 8, val = {[2] = {pos = Vector(0, 122.18, 25.56), ang = Angle(0, 180, 90), scale = 0.786}}}
}, {
	pos = Vector(0, -114.09, 47.42),
	ang = Angle(0, 0, 85.74),
	scale = 0.738,
	bg = {id = 8, val = {[2] = {pos = Vector(0, -113.58, 46.95), ang = Angle(0, 0, 83.37), scale = 1.111}}}
})

PLATE:RegisterPlate("chev_impala_09_police", {
	pos = Vector(0, 121.95, 19.36),
	ang = Angle(0, 180, 88),
	scale = 0.84,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -120, 28.1),
	ang = Angle(0, 360, 82),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("chev_suburban_pol", {
	pos = Vector(0.05, 135.9, 22.5),
	ang = Angle(0, 180, 114),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -129.2, 46.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("chev_suburban_pol_und", {
	pos = Vector(0.05, 135.9, 22.5),
	ang = Angle(0, 180, 114),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -129.2, 46.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("chev_tahoe_police_lw", {
	pos = Vector(0, 115, 20),
	ang = Angle(0, 180, 112),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -113, 47),
	ang = Angle(0, 360, 86),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("dodge_charger_2015_police_lw", {
	pos = Vector(0, 124.5, 25),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -127, 29.7),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("dodge_charger_2015_undercover_lw", {
	pos = Vector(0, 124.5, 25),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -127, 29.7),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("dodge_monaco_police_lw", {
	pos = Vector(34.1, 123.8, 18.1),
	ang = Angle(0, 180, 90),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -133.3, 26.1),
	ang = Angle(0, 0, 81),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ford_capri_rs3100_police_lw", {
	pos = Vector(0, 98.4, 17.5),
	ang = Angle(0, 180, 125),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -104, 32),
	ang = Angle(0, 360, 87),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ford_f350_ambu_lw", {
	pos = Vector(-1, -170.5, 35),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("jag_xfr_pol", {
	pos = Vector(0, 119.53, 22.6),
	ang = Angle(0, 180, 90),
	scale = 0.73,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.46, -113.63, 42.1),
	ang = Angle(0, 360, 83),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("jag_xfr_pol_und", {
	pos = Vector(0, 119.53, 22.6),
	ang = Angle(0, 180, 90),
	scale = 0.73,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.46, -113.63, 42.1),
	ang = Angle(0, 360, 83),
	scale = 0.8,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("volvo_s60_pol", {
	pos = Vector(0, 117, 36),
	ang = Angle(0, 180, 92),
	scale = 0.8,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -112.3, 54.5),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("kamaz", {
	pos = Vector(0, 172.2, 45.6),
	ang = Angle(0, 180, 90),
	scale = 1.25,
	bg = {id = false, val = {}}
}, {
	pos = Vector(-39, -166.5, 48.9),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("maz", {
	pos = Vector(-28, 199.5, 64),
	ang = Angle(0, 180, 90),
	scale = 1.4,
	bg = {id = false, val = {}}
}, {
	pos = Vector(-30.75, -188.6, 50.5),
	ang = Angle(0, 0, 90),
	scale = 0.93,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("uaz_31519", {
	pos = Vector(0, 88.5, 43),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-26.5, -81.5, 79.5),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("uaz_jag", {
	pos = Vector(0.7, 109.6, 48.4),
	ang = Angle(0, 180, 80),
	bg = {id = false, val = {}}
}, {
	pos = Vector(1.3, -103.2, 46.8),
	ang = Angle(0, 0, 85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("scionfrstdm", {
	pos = Vector(0.62, 103.43, 23.5),
	ang = Angle(0, 180, 90),
	bg = {id = 4, val = {[1] = {pos = Vector(0.62, 104.27, 24.84), ang = Angle(0, 180, 90)}, [5] = {pos = Vector(0.62, 106.57, 23.21), ang = Angle(0, 180, 90)}, [6] = {pos = Vector(0.62, 105.33, 23.5), ang = Angle(0, 180, 90)}}}
}, {
	pos = Vector(-0.66, -100, 40.2),
	ang = Angle(0, 0, 83),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("creator_nissan_datsun_510.lua", {
	pos = Vector(0, 101.82, 23.15),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -95.48, 33.82),
	ang = Angle(0, 0, 105.85),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("impalasgm", {
	pos = Vector(0, 115.51, 18.81),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -127.24, 18.84),
	ang = Angle(0, 0, 97.15),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("cobra427", {
	pos = Vector(0, -92.78, 16.52),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("cvpi_fh3_sgm", {
	pos = Vector(0, 118.85, 18.24),
	ang = Angle(0, 180, 95.75),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("cvpi_new_sgm", {
	pos = Vector(-0.27, 129.8, 20.7),
	ang = Angle(0, 180, 101.99),
	scale = 0.886,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0.3, -110.67, 36.21),
	ang = Angle(0, 0, 77.8),
	scale = 0.881,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("peelp50", {
	pos = Vector(0, -30.99, 20.05),
	ang = Angle(0, 0, 84.75),
	scale = 0.985,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("charger69sgm", {
	pos = Vector(0, -110, 22.57),
	ang = Angle(0, 0, 98.12),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("rtrx_new_sgm", {
	pos = Vector(0, -113.44, 15.17),
	ang = Angle(0, 0, 99.16),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("17raptor_sgm", {
	pos = Vector(1.27, -117.41, 34.65),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("15gt_new_sgm", {
	pos = Vector(0, 102.75, 21.36),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -103.06, 26.84),
	ang = Angle(0, 0, 71.31),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("16fpiu_new_sgm", {
	pos = Vector(0, -114.15, 49.2),
	ang = Angle(0, 0, 69.53),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("oldambu_toki", {
	pos = Vector(-0.24, 147.03, 24.57),
	ang = Angle(0, 180, 90),
	scale = 1.07,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -154.05, 28.56),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("squad1_toki", {
	pos = Vector(0, 189.74, 35.58),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-47.97, -135.3, 45.52),
	ang = Angle(0, 0, 90),
	scale = 0.858,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("express_toki", {
	pos = Vector(0, 140.4, 21.62),
	ang = Angle(0, 180, 97.36),
	bg = {id = false, val = {}}
}, {
	pos = Vector(16.64, -159.96, 48.02),
	ang = Angle(0, 0, 90),
	scale = 0.907,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("scania09jigtdm", {
	pos = Vector(0, 105.37, 21.92),
	ang = Angle(180, 0, -91.5),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-35.04, -122.39, 25.33),
	ang = Angle(0, 0, 87.46),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("scania09tdm", {
	pos = Vector(0, 105.31, 21.9),
	ang = Angle(180, 0, -91.5),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-35.37, -122.53, 25.37),
	ang = Angle(0, 0, 90),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("volvofh16shorttdm", {
	pos = Vector(0, 117.45, 16.39),
	ang = Angle(0, 180, 90),
	scale = 0.78,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -116, 27.8),
	ang = Angle(0, 0, 90),
	scale = 1.2,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("volvofh16longtdm", {
	pos = Vector(0, 117.44, 16.45),
	ang = Angle(0, 180, 90),
	scale = 0.78,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -124.65, 28.8),
	ang = Angle(0, 0, 90),
	scale = 1.2,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("creator_vauxhall_agila", {
	pos = Vector(0, 81.91, 23.11),
	ang = Angle(0, 180, 84.21),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -99.61, 25.56),
	ang = Angle(0, 0, 77.46),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("faggio_sgm", {
	pos = Vector(0, -29.16, 21.74),
	ang = Angle(0, 0, 56.92),
	scale = 0.537,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("swtruck002", {
	pos = Vector(0, 146.15, 23.83),
	ang = Angle(0, 180, 90),
	scale = 1.414,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -118.45, 38.59),
	ang = Angle(0, 0, 90),
	scale = 1.225,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("swtruck001", {
	pos = Vector(0, 146, 26.99),
	ang = Angle(0, 180, 90),
	scale = 1.414,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -118.45, 38.59),
	ang = Angle(0, 0, 90),
	scale = 1.225,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("swtruck003", {
	pos = Vector(0, 179.95, 30.48),
	ang = Angle(0, 180, 90),
	scale = 1.414,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -172.29, 34.26),
	ang = Angle(0, 0, 90),
	scale = 1.225,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("swtruck004", {
	pos = Vector(0, 180.01, 28.86),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -172.51, 34.52),
	ang = Angle(0, 0, 90),
	scale = 1.306,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("swtruck005", {
	pos = Vector(0, 179.76, 27.73),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -172.59, 34.44),
	ang = Angle(0, 0, 90),
	scale = 1.457,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("swtruck006", {
	pos = Vector(4.95, 180.01, 28.86),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -172.51, 34.52),
	ang = Angle(0, 0, 90),
	scale = 1.306,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("creator_smart_fortwo_2015", {
	pos = Vector(0, 65.19, 23.46),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -61.9, 42.37),
	ang = Angle(0, 0, 85.92),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ctv_infiniti_q60_concept", {
	pos = Vector(4.08, 101.98, 10),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(5.94, -116.72, 21.64),
	ang = Angle(0.89, 0.36, 86.04),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("ctv_bugatti_divo", {
	pos = Vector(0, -117.26, 30.67),
	ang = Angle(0, 0.18, 88.58),
	scale = 1.057,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("vcars_porschegt3", {
	pos = Vector(-0.3, -109.7, 25.78),
	ang = Angle(0, 0, 79.25),
	bg = {id = 1, val = {[1] = {pos = Vector(-0.3, -109.36, 25.7), ang = Angle(0, 0, 79.25)}}}
})

PLATE:RegisterPlate("azok30_caddy_limousine", {
	pos = Vector(0, 124.5, 8.61),
	ang = Angle(0, 180, 83.65),
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -127.05, 8.34),
	ang = Angle(0, 0, 90),
	scale = 0.842,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("azok30_citroen_berlingo_2017", {
	pos = Vector(0, 113.92, 15.04),
	ang = Angle(0, 180, 90),
	scale = 0.756,
	bg = {id = false, val = {}}
}, {
	pos = Vector(-13.97, -92.82, 20.61),
	ang = Angle(0, 0, 76.41),
	scale = 0.842,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("GENDARMERIE - Peugeot 208 GTi", {
	pos = Vector(0, 101, 15.98),
	ang = Angle(0, 180, 87.07),
	scale = 0.756,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -70.01, 26.9),
	ang = Angle(0, 0, 67.89),
	scale = 0.842,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("GENDARMERIE - Peugeot Bipper", {
	pos = Vector(0.06, 103.72, 13.8),
	ang = Angle(0, 180, 90),
	bg = {id = false, val = {}}
}, {
	pos = Vector(-12.42, -79.55, 22.52),
	ang = Angle(0.36, -1.16, 83.74),
	scale = 1.105,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("GENDARMERIE - Renault Zoe", {
	pos = Vector(-0.13, 92.08, 7.57),
	ang = Angle(0, 180, 90),
	scale = 0.659,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -76.49, 26.44),
	ang = Angle(0, 0, 73.54),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("azok30_honda_450_crf", {
	pos = Vector(-0.03, -38.74, 32.68),
	ang = Angle(0.17, -0.7, 119.09),
	scale = 0.434,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("azok30_ktm_690_smc_r_2019", {
	pos = Vector(0.05, -42.77, 25.58),
	ang = Angle(0.01, 0, 57.64),
	scale = 0.602,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("azok30_ktm_690_smc_r", {
	pos = Vector(0.05, -40.91, 23.08),
	ang = Angle(0.01, 0, 57.64),
	scale = 0.602,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("azok30_lamborghini_urus", {
	pos = Vector(0, 118.62, 16.13),
	ang = Angle(0, 180, 90),
	scale = 0.594,
	bg = {id = false, val = {}}
}, {
	pos = Vector(0, -112.38, 35.53),
	ang = Angle(0, 0, 76),
	scale = 0.647,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("azok30_mbk_booster_spirit", {
	pos = Vector(0, 28.7, 20.71),
	ang = Angle(0, 180, 31.87),
	scale = 0.557,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("azok30_mercedes_classe_a_2019", {
	pos = Vector(0, -111.13, 27.55),
	ang = Angle(0, 0, 84.61),
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("azok30_merc_s63_cab_black", {
	pos = Vector(0, -110.06, 18.95),
	ang = Angle(0, 0, 75.73),
	scale = 0.89,
	bg = {id = false, val = {}}
})

PLATE:RegisterPlate("azok30_merc_s63_cab", {
	pos = Vector(0, -110.06, 18.95),
	ang = Angle(0, 0, 75.73),
	scale = 0.89,
	bg = {id = false, val = {}}
})
